name: check-pr

on:
  workflow_dispatch:
  pull_request:
jobs:

  create-pkg-list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
    - id: matrix
      run: |
        script=$(./utils/make-matrix.sh)
        echo "matrix=${script}" >> $GITHUB_OUTPUT

  build:
    needs: [ create-pkg-list]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.create-pkg-list.outputs.matrix) }}
    container:
      image: ghcr.io/brokenpip3/my-pkgbuilds:main
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files in the packages folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: packages/${{ matrix.pkg }}/*
      - name: Build
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        working-directory: "packages/${{ matrix.pkg }}"
        run: |
          sudo pacman -Syu --noconfirm
          makepkg -s -o --noconfirm
          makepkg -sc --noconfirm
          makepkg --printsrcinfo > .SRCINFO
